name: Tests

on:
  push:
    branches: [ main ] # Run on pushes to main branch
  pull_request:
    branches: [ main ] # Run on pull requests to main branch

jobs:
  test:

    runs-on: ubuntu-latest # or macOS-latest, or windows-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x] # 16.x is the current LTS version

    steps:
      - uses: actions/checkout@v3 # Checkout the code
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }} # Node.js version to use
      - run: npm config set legacy-peer-deps true
      - run: npm ci # install dependencies
      - run: npm run dep:update # update dependencies
      - run: npm run test
